/**
 * @license
 * Copyright (c) 2018 THREEANGLE SOFTWARE SOLUTIONS SRL
 * Available under MIT license webFrame/LICENSE
 */

// tslint:disable:no-duplicate-string
export let products = [
        {
            id: 9134,
            asin: 'B000QD5U0Q',
            name: '"LOVE BEAT" HEARTBEAT BABY BLANKET',
            product_url: 'http://www.amazon.com/dp/B000QD5U0Q',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/41uJgmCOSEL._SS75_.jpg',
            country: 'US',
            price: null,
            fees: 19.34,
            currency_code: 'USD',
            rating: 3.4,
            no_reviews: 11,
            no_sellers: null,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 28,
            pim_category_id: 1,
            created_at: '2019-03-13T10:16:01.940Z',
            updated_at: '2019-03-13T11:14:46.138Z',
            marketplace_asin: 'us/B000QD5U0Q  ',
            brand: 'Love Beat',
            image_urls: '51fTM00R1JL.jpg',
            sales: 0,
            revenue: null,
            initial_cost: null,
            initial_net_profit: null,
            net_profit: null,
            price_change_last_ninety_days: null,
            review_count_change_monthly: 0,
            review_rate: null,
            sales_change_last_ninety_days: -100,
            sales_last_year: 5,
            sales_to_reviews: 0,
            unit_margin: null,
        },
        {
            id: 19931,
            asin: 'B002WW91AO',
            name: '"Chicago Cubs Major League Baseball Collection" 9" Round, Party Plates',
            product_url: 'http://www.amazon.com/dp/B002WW91AO',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/61zry4vGQJL._SS75_.jpg',
            country: 'US',
            price: 8.66,
            fees: 5.05,
            currency_code: 'USD',
            rating: 4.5,
            no_reviews: 10,
            no_sellers: 5,
            estimated_sales: 48,
            estimated_revenue: 596.16,
            listing_quality_score: 34,
            pim_category_id: 7,
            created_at: '2019-03-18T07:14:41.546Z',
            updated_at: '2019-03-18T07:14:41.546Z',
            marketplace_asin: 'us/B002WW91AO  ',
            brand: 'Amscan',
            image_urls: '61zry4vGQJL.jpg',
            sales: 36,
            revenue: 311.76,
            initial_cost: 84.44,
            initial_net_profit: 22.86,
            net_profit: 149.4,
            price_change_last_ninety_days: 10.99,
            review_count_change_monthly: 0,
            review_rate: 0,
            sales_change_last_ninety_days: 193.67,
            sales_last_year: 567,
            sales_to_reviews: 3.6,
            unit_margin: 4.15,
        },
        {
            id: 63,
            asin: 'B002YOVF90',
            name: 'Fujifilm INSTAX 210 Instant Photo Camera Kit with 5 Twin Pack of INSTAX Film',
            product_url: 'http://www.amazon.com/dp/B002YOVF90',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/51AdOqLSGML._SS75_.jpg',
            country: 'US',
            price: null,
            fees: 13.28,
            currency_code: 'USD',
            rating: 4.3,
            no_reviews: 372,
            no_sellers: null,
            estimated_sales: 13,
            estimated_revenue: 675.87,
            listing_quality_score: 50,
            pim_category_id: 3,
            created_at: '2019-02-22T21:22:53.600Z',
            updated_at: '2019-03-13T11:18:46.387Z',
            marketplace_asin: 'us/B002YOVF90  ',
            brand: 'Fujifilm',
            image_urls: '81PKOJl8ihL.jpg',
            sales: 7,
            revenue: null,
            initial_cost: null,
            initial_net_profit: null,
            net_profit: null,
            price_change_last_ninety_days: null,
            review_count_change_monthly: 0,
            review_rate: 0,
            sales_change_last_ninety_days: 14.35,
            sales_last_year: 116,
            sales_to_reviews: 0.02,
            unit_margin: null,
        },
        {
            id: 636,
            asin: 'B002Z8LDR4',
            name: '10 Pack of Plain Glossy White Disposable 35mm Cameras for Wedding or Any Party, 27exp',
            product_url: 'http://www.amazon.com/dp/B002Z8LDR4',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/51uBUMB22xL._SS75_.jpg',
            country: 'US',
            price: 64.99,
            fees: null,
            currency_code: 'USD',
            rating: 3.7,
            no_reviews: 34,
            no_sellers: 1,
            estimated_sales: 3,
            estimated_revenue: 194.97,
            listing_quality_score: 40,
            pim_category_id: 3,
            created_at: '2019-02-22T21:22:53.534Z',
            updated_at: '2019-03-13T11:18:46.327Z',
            marketplace_asin: 'us/B002Z8LDR4  ',
            brand: 'The Camera Depot',
            image_urls: '51uBUMB22xL.jpg',
            sales: 18,
            revenue: 1169.82,
            initial_cost: 373.69,
            initial_net_profit: 592.04,
            net_profit: 1076.22,
            price_change_last_ninety_days: 0,
            review_count_change_monthly: 0,
            review_rate: 0,
            sales_change_last_ninety_days: 134.74,
            sales_last_year: 297,
            sales_to_reviews: 0.53,
            unit_margin: 59.79,
        },
        {
            id: 9162,
            asin: 'B004C49GS2',
            name: '1 X Bananafish Mosaic Jungle Plush Blanket',
            product_url: 'http://www.amazon.com/dp/B004C49GS2',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/51F5QCkbIRL._SS75_.jpg',
            country: 'US',
            price: null,
            fees: 6.01,
            currency_code: 'USD',
            rating: 4.8,
            no_reviews: 5,
            no_sellers: null,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 22,
            pim_category_id: 1,
            created_at: '2019-03-13T10:17:00.637Z',
            updated_at: '2019-03-13T11:15:00.714Z',
            marketplace_asin: 'us/B004C49GS2  ',
            brand: 'Rosenberry Rooms',
            image_urls: '51F5QCkbIRL.jpg',
            sales: 0,
            revenue: null,
            initial_cost: null,
            initial_net_profit: null,
            net_profit: null,
            price_change_last_ninety_days: null,
            review_count_change_monthly: 0,
            review_rate: null,
            sales_change_last_ninety_days: -100,
            sales_last_year: 8,
            sales_to_reviews: 0,
            unit_margin: null,
        },
        {
            id: 21897,
            asin: 'B004E3JE4W',
            name: "*Seeds and Things Okra Seeds - 'Red Burgundy' Vegetable Seed Packet (100 Seeds)",
            product_url: 'http://www.amazon.com/dp/B004E3JE4W',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/410Z%2B39pkXL._SS75_.jpg',
            country: 'US',
            price: 2.86,
            fees: null,
            currency_code: 'USD',
            rating: 3.6,
            no_reviews: 25,
            no_sellers: 5,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 45,
            pim_category_id: 9,
            created_at: '2019-03-18T07:21:21.215Z',
            updated_at: '2019-03-18T07:21:21.215Z',
            marketplace_asin: 'us/B004E3JE4W  ',
            brand: null,
            image_urls: '410Z%2B39pkXL.jpg;31xfqYbZx-L.jpg;41k63Q-qsqL.jpg',
            sales: 2,
            revenue: 5.72,
            initial_cost: 1.43,
            initial_net_profit: 2.29,
            net_profit: 3.72,
            price_change_last_ninety_days: null,
            review_count_change_monthly: null,
            review_rate: 0,
            sales_change_last_ninety_days: null,
            sales_last_year: 19,
            sales_to_reviews: 0.08,
            unit_margin: 1.86,
        },
        {
            id: 18120,
            asin: 'B004FJFNAO',
            name: '2TB G-speed Es Pro Xl Disk',
            product_url: 'http://www.amazon.com/dp/B004FJFNAO',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/41RW1Y6sy3L._SS75_.jpg',
            country: 'US',
            price: 490.59,
            fees: 35.91,
            currency_code: 'USD',
            rating: null,
            no_reviews: 0,
            no_sellers: 1,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 19,
            pim_category_id: 5,
            created_at: '2019-03-13T11:27:31.082Z',
            updated_at: '2019-03-13T11:27:31.082Z',
            marketplace_asin: 'us/B004FJFNAO  ',
            brand: 'G-Technology',
            image_urls: '41RW1Y6sy3L.jpg',
            sales: 0,
            revenue: 0,
            initial_cost: 0,
            initial_net_profit: 0,
            net_profit: 0,
            price_change_last_ninety_days: 0,
            review_count_change_monthly: null,
            review_rate: null,
            sales_change_last_ninety_days: -100,
            sales_last_year: 0,
            sales_to_reviews: null,
            unit_margin: 431.72,
        },
        {
            id: 25611,
            asin: 'B004XHXJMW',
            name: '"Boston Red Sox Major League Baseball Collection" Loot Bags, Party Favor',
            product_url: 'http://www.amazon.com/dp/B004XHXJMW',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/51o0onWEEtL._SS75_.jpg',
            country: 'US',
            price: 4.19,
            fees: 3.41,
            currency_code: 'USD',
            rating: 2,
            no_reviews: 1,
            no_sellers: 4,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 39,
            pim_category_id: 12,
            created_at: '2019-03-18T07:33:41.211Z',
            updated_at: '2019-03-18T07:33:41.211Z',
            marketplace_asin: 'us/B004XHXJMW  ',
            brand: 'Amscan',
            image_urls: '51o0onWEEtL.jpg;61nC0D8YdnL.jpg',
            sales: 12,
            revenue: 50.28,
            initial_cost: 11.52,
            initial_net_profit: -2.94,
            net_profit: 9.36,
            price_change_last_ninety_days: 57.4,
            review_count_change_monthly: 0,
            review_rate: 0,
            sales_change_last_ninety_days: 107.77,
            sales_last_year: 138,
            sales_to_reviews: 12,
            unit_margin: 0.78,
        },
        {
            id: 15744,
            asin: 'B0057PDVS6',
            name: '10 Rolls Fujifilm APS 200 25 Exp Film Nexia Advanced Photo System',
            product_url: 'http://www.amazon.com/dp/B0057PDVS6',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/31eGrf-OXdL._SS75_.jpg',
            country: 'US',
            price: 64.95,
            fees: null,
            currency_code: 'USD',
            rating: 3.8,
            no_reviews: 2,
            no_sellers: 1,
            estimated_sales: 0,
            estimated_revenue: 0,
            listing_quality_score: 33,
            pim_category_id: 3,
            created_at: '2019-03-13T11:20:31.286Z',
            updated_at: '2019-03-13T11:20:31.286Z',
            marketplace_asin: 'us/B0057PDVS6  ',
            brand: 'Nexia Advanced Photo System',
            image_urls: '31eGrf-OXdL.jpg',
            sales: 0,
            revenue: 0,
            initial_cost: 0,
            initial_net_profit: 0,
            net_profit: 0,
            price_change_last_ninety_days: 0,
            review_count_change_monthly: 0,
            review_rate: null,
            sales_change_last_ninety_days: -100,
            sales_last_year: 7,
            sales_to_reviews: 0,
            unit_margin: 59.75,
        },
        {
            id: 22311,
            asin: 'B005I5FG6A',
            name: '1 Gallon Cedar Sauna Bucket, Plastic Liner with Cedar Dipper',
            product_url: 'http://www.amazon.com/dp/B005I5FG6A',
            image_url: 'https://images-na.ssl-images-amazon.com/images/I/51Pe5QPYbPL._SS75_.jpg',
            country: 'US',
            price: 46.99,
            fees: null,
            currency_code: 'USD',
            rating: 3.4,
            no_reviews: 6,
            no_sellers: 1,
            estimated_sales: 39,
            estimated_revenue: 1832.61,
            listing_quality_score: 31,
            pim_category_id: 9,
            created_at: '2019-03-18T07:22:41.283Z',
            updated_at: '2019-03-18T07:22:41.283Z',
            marketplace_asin: 'us/B005I5FG6A  ',
            brand: null,
            image_urls: '51Pe5QPYbPL.jpg',
            sales: 26,
            revenue: 1221.74,
            initial_cost: 352.42,
            initial_net_profit: 549.74,
            net_profit: 1038.44,
            price_change_last_ninety_days: null,
            review_count_change_monthly: null,
            review_rate: 0,
            sales_change_last_ninety_days: null,
            sales_last_year: 136,
            sales_to_reviews: 4.33,
            unit_margin: 39.94,
        },
];
