/**
 * @license
 * Copyright (c) 2018-2020 THREEANGLE SOFTWARE SOLUTIONS SRL
 * Available under MIT license webFrame/LICENSE
 */

/**
 * Provides a list of known errors for which translations exist.
 */
export enum KNOWN_ERROR_MESSAGE {
  CONNECTION_REFUSED = 'GENERAL.ERROR.CONNECTION_REFUSED',
  EXPIRED_SESSION = 'GENERAL.ERROR.EXPIRED_SESSION',
  INVALID_CREDENTIALS = 'GENERAL.ERROR.INVALID_CREDENTIALS',
  INVALID_DATA = 'GENERAL.ERROR.INVALID_DATA',
  PLEASE_UPDATE = 'GENERAL.ERROR.PLEASE_UPDATE',
  UNKNOWN_NETWORK_ERROR = 'GENERAL.ERROR.UNKNOWN_NETWORK_ERROR',
}
