/**
 * @license
 * Copyright (c) 2018-2020 THREEANGLE SOFTWARE SOLUTIONS SRL
 * Available under MIT license webFrame/LICENSE
 */

export enum USER_PERMISSION {
  ACCESS_ADMIN_PAGES = 'ACCESS_ADMIN_PAGES',
  ACCESS_SANDBOX_PAGES = 'ACCESS_SANDBOX_PAGES',
}
